Differentially Methylated Cell Type Site Finder

Align Files
```{r}
 # Load files
library(data.table)
library(dplyr)
patient_info <- '/Users/hugohudson/Desktop/Lab/GSE74193_GEO_procData.csv'
in_depth_patient_info <- '/Users/hugohudson/Desktop/Lab/GSE74193_series_matrix.csv'

col_names <- names(fread(patient_info, nrows = 0))
beta_columns <- col_names[grepl("Beta", col_names)]
methylation_df <- fread(patient_info, select = beta_columns)
col_names <- colnames(methylation_df)
patient_df <- read.csv(in_depth_patient_info)
# Create a dataframe of methylation data that is aligned with the cell fractions, i.e. exclude if we do not have cell fractions
brnum <- substr(patient_df[43, 2:ncol(patient_df)], 50, nchar(patient_df[43, 2]))
colnames(methylation_df) <- brnum
colnames(methylation_df) <- make.names(colnames(methylation_df), unique = TRUE)
uniqueDF <- select(methylation_df, colnames(methylation_df)[!grepl("\\.1$", colnames(methylation_df))])

# Now select the ones in unique that have DAN's brnums
danCSV <- read.csv('/Users/hugohudson/Downloads/psychencode_mgp_estimations.csv')
filteredDAN <- filter(danCSV, grepl('Br', danCSV$individualID))
accurateDF <- select(uniqueDF, colnames(uniqueDF)[colnames(uniqueDF) %in% filteredDAN$individualID])
danFILTER <- filteredDAN %>%
  filter(individualID %in% colnames(accurateDF))
# Make df with sorted brnum and fractions
df <- transpose(danFILTER[, 9:ncol(danFILTER)])
nextNames <- df[1, ]
df <- df[2:nrow(df), ]
colnames(df) <- nextNames
# return the above df and sorted methylation
patientData <- df[sort(colnames(df))]
methylationData <- select(accurateDF, sort(colnames(accurateDF)))
```
CellDMC
```{r}
library(EpiDISH)
# Format the fraction data
cell_types <- c("Astrocyte", "Endothelial", "IT", "L4.IT", "L5.ET", 
                "L5.6.IT.Car3", "L5.6.NP", "L6.CT", "L6b", "LAMP5", 
                "Microglia", "OPC", "Oligodendrocyte", "PAX6", 
                "PVALB", "Pericyte", "SST", "VIP", "VLMC")
# Need to scale fractions to sum to 1.
normalize_row <- function(row) {
  # Convert negative values to zero (optional, depending on how you want to handle negative values)
  row <- as.numeric(row)
  row[row < 0] <- 0
  # Normalize the row so that the sum equals 1
  normalized_values <- row / sum(row)
  return(normalized_values)
}
dfPreNormalize <- patientData[28: nrow(patientData), ]
df_normalized <- apply(t(dfPreNormalize), 1, normalize_row)
frac <- t(df_normalized)
pheno <- as.character(patientData[17, ])
binary_list <- ifelse(pheno == "Schizophrenia", 1, 0)
methylationData <- as.matrix(methylationData)
colnames(frac) <- cell_types
frac <- as.matrix(frac)
na_indices <- which(rowSums(is.na(fracel)) > 0)
frac.m_cleaned <- frac[-na_indices, ]
beta.m_cleaned <- methylationData[, -na_indices]
pheno_cleaned <- binary_list[-na_indices]
# Run CellDMC
dmcRan <- CellDMC(beta.m_cleaned, pheno_cleaned, frac.m_cleaned, mc.cores = 6)
```
Save Result
```{r}
dmcRan$dmct
# DMCT is the mask for what probes are specific

# Result is to find the specific values for each probe

# Run again, whilst covarying for age, race and cell proportion.
```

