
Load Libraries
```{r}
library(data.table)
library(dplyr)
```
File Aligner
```{r}
fileAligner <- function() {
  # Load files
  patient_info <- '/Users/hugohudson/Desktop/Lab/GSE74193_GEO_procData.csv'
  in_depth_patient_info <- '/Users/hugohudson/Desktop/Lab/GSE74193_series_matrix.csv'
  
  col_names <- names(fread(patient_info, nrows = 0))
  beta_columns <- col_names[grepl("Beta", col_names)]
  methylation_df <- fread(patient_info, select = beta_columns)
  col_names <- colnames(methylation_df)
  patient_df <- read.csv(in_depth_patient_info)
  # Create a dataframe of methylation data that is aligned with the cell fractions, i.e. exclude if we do not have cell fractions
brnum <- substr(patient_df[43, 2:ncol(patient_df)], 50, nchar(patient_df[43, 2]))
colnames(methylation_df) <- brnum
colnames(methylation_df) <- make.names(colnames(methylation_df), unique = TRUE)
uniqueDF <- select(methylation_df, colnames(methylation_df)[!grepl("\\.1$", colnames(methylation_df))])

# Now select the ones in unique that have DAN's brnums
danCSV <- read.csv('/Users/hugohudson/Downloads/psychencode_mgp_estimations.csv')
filteredDAN <- filter(danCSV, grepl('Br', danCSV$individualID))
accurateDF <- select(uniqueDF, colnames(uniqueDF)[colnames(uniqueDF) %in% filteredDAN$individualID])
danFILTER <- filteredDAN %>%
  filter(individualID %in% colnames(accurateDF))
# Make df with sorted brnum and fractions
df <- transpose(danFILTER[, 9:ncol(danFILTER)])
nextNames <- df[1, ]
df <- df[2:nrow(df), ]
colnames(df) <- nextNames
# return the above df and sorted methylation
patientData <- df[sort(colnames(df))]
methylationData <- select(accurateDF, sort(colnames(accurateDF)))
return(methylationData, patientData)
}
```